### ISSUE TITLE
Hangout #1 (Topic: Projects - 20.12.2021)

### ISSUE THREAD

**Issue by loujaybee** [openupthecloud/hangout#1]
**Topic:** Cloud resumes, and project reviews! 
**When:** 20th December, 2021. 
**Where:** [Twitter](https://twitter.com/openupthecloud/status/1469672718534688771?s=20) (Space)

**Important:** ✨If you have a resume or project you'd like to be reviewed, drop it in the comments below! ✨  🎁 Any resumes/projects that get reviewed will get a copy of: [The Tech Resume](https://thetechresume.com) or [Cloud Resume Challenge](https://cloudresumechallenge.dev/book/) (your choice!) 🎁 

### Agenda: 

* Why are cloud projects important?
* When should someone look to start building projects?
* How do you stay motivated when building a project?
* What makes a good cloud project/resume? What things should folks add? 
* What are common mistakes folks make with cloud resumes/projects? 

### Guests:

* Linda Vivah ([Twitter](https://twitter.com/lindavivah) | [Instagram](https://www.instagram.com/lindavivah/) | [YouTube](https://www.youtube.com/user/LindaVivah))
* Gwyneth Peña-Siguenza ([YouTube](https://www.youtube.com/c/MadeByGPS) | [Twitter](https://twitter.com/madebygps) | [LinkedIn](https://www.linkedin.com/in/madebygps/))
* Brian Hough ([Twitter](https://twitter.com/BrianHHough) | [Instagram](https://www.instagram.com/brianhhough/) | [YouTube](https://www.youtube.com/brianhhough) | [LinkedIn](https://www.linkedin.com/in/BrianHHough/))
* Andrew Brown ([Twitter](https://twitter.com/andrewbrown) | [LinkedIn](https://www.linkedin.com/in/andrew-wc-brown/))
* Bart Castle (aka Cloud Bart) ([Twitter](https://twitter.com/cloudbart) | [YouTube](https://www.youtube.com/c/CloudBart))
* Rishabh Kumar ([Twitter](https://twitter.com/rishabk7) | [YouTube](https://www.youtube.com/c/rishabkumar7) | [LinkedIn](https://www.linkedin.com/in/rishabkumar7/))
* Antonio Lo Fiego ([Twitter](https://twitter.com/antonio_lofiego) | [YouTube](https://www.youtube.com/channel/UC4Kz3mqchWcc9ZMibHjT3Ow))
* Lou ([Twitter](https://twitter.com/loujaybee) | [LinkedIn](https://www.linkedin.com/in/loujaybee))

Also, see: 
* Learn To Cloud ([Twitter](https://twitter.com/learntocloud) | [Instagram](https://www.instagram.com/learntocloudguide/))
* Exam Pro ([YouTube](https://www.youtube.com/c/ExamProChannel) | [Twitter](https://twitter.com/examproco))
* Open Up The Cloud ([Twitter](https://twitter.com/openupthecloud) | [Blog](https://openupthecloud.com/) | [YouTube](https://www.youtube.com/c/OpenUpTheCloud) | [LinkedIn](https://www.linkedin.com/in/openupthecloud) | [Instagram](https://www.instagram.com/openupthecloud))

---
<p align="center">
<img src="https://user-images.githubusercontent.com/5528307/146671204-363c50d1-ef7e-4def-bc6e-11121a42af6c.png" width="400" />
</p>

**Comment by nandyandcs** [comment]
Hi Lou

Here is my resume for review. I'm hoping this will get me into the cloud community 
[Nandhini Muralidharan_Solutions Architect.pdf](https://github.com/openupthecloud/hangout/files/7740846/Nandhini.Muralidharan_Solutions.Architect.pdf)

**Comment by jclm-rt** [comment]
https://resume.juliocesarlapaca.ml

https://drive.google.com/file/d/1m7b1gEcqZCmP6fqy5YBxgUonWm7xm5Bq/view?usp=drivesdk

**Comment by loujaybee** [comment]
[Daniel_Resume (4).pdf](https://github.com/openupthecloud/hangout/files/7746063/Daniel_Siefert_Resume.4.pdf)

**Comment by loujaybee** [comment]
[William](https://www.dropbox.com/s/mwd2vzuhvfzaulo/CV-Ghelfi_William-EN-Senior-Front-End-Developer.pdf?dl=0)

**Comment by loujaybee** [comment]
[Victory](https://docs.google.com/document/d/1dyyiDrtDBbZpzw94-cMMGJD9JB2IeQm7MUuguw2Bs7w/edit)

**Comment by Kumailcodes** [comment]
[https://docs.google.com/document/d/1WIppyWUhbbTtYP948iYsrB34jnwAiocw/edit] my first CV, would really appreciate your feeddback. Thank you!

**Comment by Kumailcodes** [comment]
[Link to CV](https://docs.google.com/document/d/1WIppyWUhbbTtYP948iYsrB34jnwAiocw/edit?usp=sharing&ouid=112613025062188474099&rtpof=true&sd=true)

This is my first CV, would really appreciate your feedback. Thank you!

P.s I am very new to the cloud community.

**Comment by bjones519** [comment]
Hi Lou,

Really enjoyed the Twitter Spaces talk today. A lot of great advice and resources shared. I've only been exposed to the world of DevOps and the Cloud six months ago, so any feedback is appreciated! Below is my resume: 

[Brittney's Resume](https://docs.google.com/document/d/1uNJ-zXzZXA7f0ZLEH5SO7EPHp4JmNvMv2kv9_t1LrnA/edit?usp=sharing)

Thank You!

**Comment by loujaybee** [comment]
Thanks all! 

Closing the issue now the event is done, you can [listen to the recording](https://twitter.com/openupthecloud/status/1469672673886322688) for a few weeks following the event.

But, I'll look into hosting as a podcast or something in the future so there's a more permanent home 🙏
